# Numpy Basics
__[NumPy](http://www.numpy.org/)__ is probably the most used package for scientific computing with Python.
It is basically _"a library for Python lists on steroids"_.

## The main entity

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes. NumPy’s array class is called `ndarray`. 

In [1]:
import numpy as np

myNumpyArray = np.array( [[1, 1, 2],
                          [3, 5, 8]] )

print("the numpy array: \n", myNumpyArray)

print("the shape (similar to matlab's size): ", myNumpyArray.shape)

print("the number of dimensions: ", myNumpyArray.ndim)

print("the number of elements: ", myNumpyArray.size)

print("the type of the elements: ", myNumpyArray.dtype)

the numpy array: 
 [[1 1 2]
 [3 5 8]]
the shape (similar to matlab's size):  (2, 3)
the number of dimensions:  2
the number of elements:  6
the type of the elements:  int64


## Array Creation
NumPy provides handy functions to initialize arrays.

In [2]:
import numpy as np

# zeros (as in Matlab)
zeros = np.zeros((2, 3))
print("zeros: \n", zeros)

# notice the "double" brackets! They come from the extended declaration:
# zeros = np.zeros(shape=(2, 3), type=float) 

# ones
ones = np.ones((3, 2))
print("ones: \n", ones)

# arange
arange = np.arange(1, 10, 2)
print("arange: ", arange)

# linspace
linspace = np.linspace(1, 10, 3)
print("linspace: ", linspace)

zeros: 
 [[0. 0. 0.]
 [0. 0. 0.]]
ones: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
arange:  [1 3 5 7 9]
linspace:  [ 1.   5.5 10. ]


## Operations
In NumPy all operations on `ndarray` are element-wise operations.

_Remark:_ the `ndarrays` must have the same shape!

In [3]:
import numpy as np

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

# addition
print("a + b: ", a + b)

# substraction
print("a - b: ", a - b)

# multiplication
print("a * b: ", a * b)

# division
print("a / b: ", a / b)

a + b:  [[ 6  8]
 [10 12]]
a - b:  [[-4 -4]
 [-4 -4]]
a * b:  [[ 5 12]
 [21 32]]
a / b:  [[0.2        0.33333333]
 [0.42857143 0.5       ]]


And for matrix multiplication one needs to use **.dot**.

In [4]:
# matrix multiplication
print("a.dot(b): ", a.dot(b))

a.dot(b):  [[19 22]
 [43 50]]


### Mathematical Operations
NumPy provides implementations for the operations we commonly use:

In [5]:
import numpy as np

a = np.arange(1, 5)
b = np.arange(-2, 3)

# exponentiation
print("a**2: ", a**2)
print("np.exp(a): ", np.exp(a))

# square root
print("np.sqrt(a): ", np.sqrt(a))

# positive part
print("positive part of b: ", b.clip(0, np.inf))

# negative part
print("negative part of b: ", b.clip(-np.inf, 0))

a**2:  [ 1  4  9 16]
np.exp(a):  [ 2.71828183  7.3890561  20.08553692 54.59815003]
np.sqrt(a):  [1.         1.41421356 1.73205081 2.        ]
positive part of b:  [0. 0. 0. 1. 2.]
negative part of b:  [-2. -1.  0.  0.  0.]


### Reduction Operations
NumPy also provides implementations for the usual reduction operations:

In [6]:
import numpy as np

a = np.arange(1, 5)

# sum
print("sum: ", a.sum())
print("sum: ", np.sum(a))

# mean
print("mean: ", a.mean())
print("mean: ", np.mean(a))

# standard deviation
print("standard deviation: ", a.std())
print("standard deviation: ", np.std(a, ddof = 1)) # denominator is N - ddof

# max/min
print("max: ", a.max())
print("min: ", np.min(a))

?a.std

sum:  10
sum:  10
mean:  2.5
mean:  2.5
standard deviation:  1.118033988749895
standard deviation:  1.2909944487358056
max:  4
min:  1


### Shape Manipulation Operations
NumPy provides as well handy operations to play with the shape of an array:

In [7]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

# transpose
print("a transposed: ", a.T)
print("a transposed shape: ", a.T.shape)

# flatten
print("a flattened: ", a.ravel())

# reshape
print("a reshaped to (3,2): ", a.reshape(3,2))

a transposed:  [[1 4]
 [2 5]
 [3 6]]
a transposed shape:  (3, 2)
a flattened:  [1 2 3 4 5 6]
a reshaped to (3,2):  [[1 2]
 [3 4]
 [5 6]]


## Random Number Generator
NumPy offers different functions for random sampling in its **random** module.

In [8]:
import numpy as np

# uniform in [0,1)
print("uniform in [0,1]: ", np.random.rand(2,1))

uniform in [0,1]:  [[0.90389947]
 [0.47619225]]


In [9]:
import numpy as np

# standard normal
print("standard normal: ", np.random.randn(2,1))

standard normal:  [[-0.68395712]
 [-0.92970243]]


In [10]:
import numpy as np

# discrete uniform
print("discrete uniform: ", np.random.randint(-1, 5, (2,1)))

discrete uniform:  [[1]
 [3]]


It provides as well sampling from many of the usual distributions:

In [11]:
import numpy as np

# binomial
print("binomial: ", np.random.binomial(2, 0.5))

# exponential
lambda_parameter = 2
print("exponential: ", np.random.exponential(1/lambda_parameter))

# poisson
print("poisson: ", np.random.poisson(lambda_parameter))

binomial:  0
exponential:  0.20358625016837273
poisson:  2


## Other Resources
* __[NumPy Reference Guide](https://docs.scipy.org/doc/numpy/reference/index.html)__
* __[SciPy Reference Guide](https://docs.scipy.org/doc/scipy/reference/)__. It's an open source library, from the same ecosystem as NumPy, that contains more advanced algorithms. For example it provides routines for numerical integration and optimization.